// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/customer/customer.proto

package customer

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVerifyCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeReq) Reset() {
	*x = GetVerifyCodeReq{}
	mi := &file_api_customer_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReq) ProtoMessage() {}

func (x *GetVerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReq.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_api_customer_customer_proto_rawDescGZIP(), []int{0}
}

func (x *GetVerifyCodeReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

type GetVerifyCodeResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VerifyCode     string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	VerifyCodeTime int64                  `protobuf:"varint,4,opt,name=verify_code_time,json=verifyCodeTime,proto3" json:"verify_code_time,omitempty"`
	VerifyCodeLife int32                  `protobuf:"varint,5,opt,name=verify_code_life,json=verifyCodeLife,proto3" json:"verify_code_life,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVerifyCodeResp) Reset() {
	*x = GetVerifyCodeResp{}
	mi := &file_api_customer_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeResp) ProtoMessage() {}

func (x *GetVerifyCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeResp.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeResp) Descriptor() ([]byte, []int) {
	return file_api_customer_customer_proto_rawDescGZIP(), []int{1}
}

func (x *GetVerifyCodeResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVerifyCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVerifyCodeResp) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *GetVerifyCodeResp) GetVerifyCodeTime() int64 {
	if x != nil {
		return x.VerifyCodeTime
	}
	return 0
}

func (x *GetVerifyCodeResp) GetVerifyCodeLife() int32 {
	if x != nil {
		return x.VerifyCodeLife
	}
	return 0
}

var File_api_customer_customer_proto protoreflect.FileDescriptor

const file_api_customer_customer_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/customer/customer.proto\x12\fapi.customer\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x10GetVerifyCodeReq\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\"\xb6\x01\n" +
	"\x11GetVerifyCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\x12(\n" +
	"\x10verify_code_time\x18\x04 \x01(\x03R\x0everifyCodeTime\x12(\n" +
	"\x10verify_code_life\x18\x05 \x01(\x05R\x0everifyCodeLife2\x8b\x01\n" +
	"\bCustomer\x12\x7f\n" +
	"\rGetVerifyCode\x12\x1e.api.customer.GetVerifyCodeReq\x1a\x1f.api.customer.GetVerifyCodeResp\"-\x82\xd3\xe4\x93\x02'\x12%/customer/get-verify-code/{telephone}B Z\x1ecustomer/api/customer;customerb\x06proto3"

var (
	file_api_customer_customer_proto_rawDescOnce sync.Once
	file_api_customer_customer_proto_rawDescData []byte
)

func file_api_customer_customer_proto_rawDescGZIP() []byte {
	file_api_customer_customer_proto_rawDescOnce.Do(func() {
		file_api_customer_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_customer_customer_proto_rawDesc), len(file_api_customer_customer_proto_rawDesc)))
	})
	return file_api_customer_customer_proto_rawDescData
}

var file_api_customer_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_customer_customer_proto_goTypes = []any{
	(*GetVerifyCodeReq)(nil),  // 0: api.customer.GetVerifyCodeReq
	(*GetVerifyCodeResp)(nil), // 1: api.customer.GetVerifyCodeResp
}
var file_api_customer_customer_proto_depIdxs = []int32{
	0, // 0: api.customer.Customer.GetVerifyCode:input_type -> api.customer.GetVerifyCodeReq
	1, // 1: api.customer.Customer.GetVerifyCode:output_type -> api.customer.GetVerifyCodeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_customer_customer_proto_init() }
func file_api_customer_customer_proto_init() {
	if File_api_customer_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_customer_customer_proto_rawDesc), len(file_api_customer_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_customer_customer_proto_goTypes,
		DependencyIndexes: file_api_customer_customer_proto_depIdxs,
		MessageInfos:      file_api_customer_customer_proto_msgTypes,
	}.Build()
	File_api_customer_customer_proto = out.File
	file_api_customer_customer_proto_goTypes = nil
	file_api_customer_customer_proto_depIdxs = nil
}
