// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/verityCode/verityCode.proto

package verityCode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TYPE int32

const (
	TYPE_DEFAULT TYPE = 0
	TYPE_DIGIT   TYPE = 1
	TYPE_LETTER  TYPE = 2
	TYPE_MIXED   TYPE = 3
)

// Enum value maps for TYPE.
var (
	TYPE_name = map[int32]string{
		0: "DEFAULT",
		1: "DIGIT",
		2: "LETTER",
		3: "MIXED",
	}
	TYPE_value = map[string]int32{
		"DEFAULT": 0,
		"DIGIT":   1,
		"LETTER":  2,
		"MIXED":   3,
	}
)

func (x TYPE) Enum() *TYPE {
	p := new(TYPE)
	*p = x
	return p
}

func (x TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_api_verityCode_verityCode_proto_enumTypes[0].Descriptor()
}

func (TYPE) Type() protoreflect.EnumType {
	return &file_api_verityCode_verityCode_proto_enumTypes[0]
}

func (x TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE.Descriptor instead.
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return file_api_verityCode_verityCode_proto_rawDescGZIP(), []int{0}
}

// 请求数据参数结构
type GetVerityCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint32                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Type          TYPE                   `protobuf:"varint,2,opt,name=type,proto3,enum=api.verityCode.TYPE" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerityCodeRequest) Reset() {
	*x = GetVerityCodeRequest{}
	mi := &file_api_verityCode_verityCode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerityCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerityCodeRequest) ProtoMessage() {}

func (x *GetVerityCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verityCode_verityCode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerityCodeRequest.ProtoReflect.Descriptor instead.
func (*GetVerityCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_verityCode_verityCode_proto_rawDescGZIP(), []int{0}
}

func (x *GetVerityCodeRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetVerityCodeRequest) GetType() TYPE {
	if x != nil {
		return x.Type
	}
	return TYPE_DEFAULT
}

// 接口返回值结构
type GetVerityCodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerityCodeReply) Reset() {
	*x = GetVerityCodeReply{}
	mi := &file_api_verityCode_verityCode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerityCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerityCodeReply) ProtoMessage() {}

func (x *GetVerityCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verityCode_verityCode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerityCodeReply.ProtoReflect.Descriptor instead.
func (*GetVerityCodeReply) Descriptor() ([]byte, []int) {
	return file_api_verityCode_verityCode_proto_rawDescGZIP(), []int{1}
}

func (x *GetVerityCodeReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_api_verityCode_verityCode_proto protoreflect.FileDescriptor

const file_api_verityCode_verityCode_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/verityCode/verityCode.proto\x12\x0eapi.verityCode\"X\n" +
	"\x14GetVerityCodeRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\rR\x06length\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.api.verityCode.TYPER\x04type\"(\n" +
	"\x12GetVerityCodeReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code*5\n" +
	"\x04TYPE\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\t\n" +
	"\x05DIGIT\x10\x01\x12\n" +
	"\n" +
	"\x06LETTER\x10\x02\x12\t\n" +
	"\x05MIXED\x10\x032g\n" +
	"\n" +
	"VerityCode\x12Y\n" +
	"\rGetVerityCode\x12$.api.verityCode.GetVerityCodeRequest\x1a\".api.verityCode.GetVerityCodeReplyB8\n" +
	"\x0eapi.verityCodeP\x01Z$verifyCode/api/verityCode;verityCodeb\x06proto3"

var (
	file_api_verityCode_verityCode_proto_rawDescOnce sync.Once
	file_api_verityCode_verityCode_proto_rawDescData []byte
)

func file_api_verityCode_verityCode_proto_rawDescGZIP() []byte {
	file_api_verityCode_verityCode_proto_rawDescOnce.Do(func() {
		file_api_verityCode_verityCode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_verityCode_verityCode_proto_rawDesc), len(file_api_verityCode_verityCode_proto_rawDesc)))
	})
	return file_api_verityCode_verityCode_proto_rawDescData
}

var file_api_verityCode_verityCode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_verityCode_verityCode_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_verityCode_verityCode_proto_goTypes = []any{
	(TYPE)(0),                    // 0: api.verityCode.TYPE
	(*GetVerityCodeRequest)(nil), // 1: api.verityCode.GetVerityCodeRequest
	(*GetVerityCodeReply)(nil),   // 2: api.verityCode.GetVerityCodeReply
}
var file_api_verityCode_verityCode_proto_depIdxs = []int32{
	0, // 0: api.verityCode.GetVerityCodeRequest.type:type_name -> api.verityCode.TYPE
	1, // 1: api.verityCode.VerityCode.GetVerityCode:input_type -> api.verityCode.GetVerityCodeRequest
	2, // 2: api.verityCode.VerityCode.GetVerityCode:output_type -> api.verityCode.GetVerityCodeReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_verityCode_verityCode_proto_init() }
func file_api_verityCode_verityCode_proto_init() {
	if File_api_verityCode_verityCode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_verityCode_verityCode_proto_rawDesc), len(file_api_verityCode_verityCode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_verityCode_verityCode_proto_goTypes,
		DependencyIndexes: file_api_verityCode_verityCode_proto_depIdxs,
		EnumInfos:         file_api_verityCode_verityCode_proto_enumTypes,
		MessageInfos:      file_api_verityCode_verityCode_proto_msgTypes,
	}.Build()
	File_api_verityCode_verityCode_proto = out.File
	file_api_verityCode_verityCode_proto_goTypes = nil
	file_api_verityCode_verityCode_proto_depIdxs = nil
}
