// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: api/verityCode/verityCode.proto

package verityCode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VerityCode_GetVerityCode_FullMethodName = "/api.verityCode.VerityCode/GetVerityCode"
)

// VerityCodeClient is the client API for VerityCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerityCodeClient interface {
	GetVerityCode(ctx context.Context, in *GetVerityCodeRequest, opts ...grpc.CallOption) (*GetVerityCodeReply, error)
}

type verityCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewVerityCodeClient(cc grpc.ClientConnInterface) VerityCodeClient {
	return &verityCodeClient{cc}
}

func (c *verityCodeClient) GetVerityCode(ctx context.Context, in *GetVerityCodeRequest, opts ...grpc.CallOption) (*GetVerityCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerityCodeReply)
	err := c.cc.Invoke(ctx, VerityCode_GetVerityCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerityCodeServer is the server API for VerityCode service.
// All implementations must embed UnimplementedVerityCodeServer
// for forward compatibility.
type VerityCodeServer interface {
	GetVerityCode(context.Context, *GetVerityCodeRequest) (*GetVerityCodeReply, error)
	mustEmbedUnimplementedVerityCodeServer()
}

// UnimplementedVerityCodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerityCodeServer struct{}

func (UnimplementedVerityCodeServer) GetVerityCode(context.Context, *GetVerityCodeRequest) (*GetVerityCodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVerityCode not implemented")
}
func (UnimplementedVerityCodeServer) mustEmbedUnimplementedVerityCodeServer() {}
func (UnimplementedVerityCodeServer) testEmbeddedByValue()                    {}

// UnsafeVerityCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerityCodeServer will
// result in compilation errors.
type UnsafeVerityCodeServer interface {
	mustEmbedUnimplementedVerityCodeServer()
}

func RegisterVerityCodeServer(s grpc.ServiceRegistrar, srv VerityCodeServer) {
	// If the following call panics, it indicates UnimplementedVerityCodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VerityCode_ServiceDesc, srv)
}

func _VerityCode_GetVerityCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerityCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerityCodeServer).GetVerityCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VerityCode_GetVerityCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerityCodeServer).GetVerityCode(ctx, req.(*GetVerityCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VerityCode_ServiceDesc is the grpc.ServiceDesc for VerityCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerityCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.verityCode.VerityCode",
	HandlerType: (*VerityCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVerityCode",
			Handler:    _VerityCode_GetVerityCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/verityCode/verityCode.proto",
}
