// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: api/driver/driver.proto

package driver

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDNoCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Idno          string                 `protobuf:"bytes,2,opt,name=idno,proto3" json:"idno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDNoCheckReq) Reset() {
	*x = IDNoCheckReq{}
	mi := &file_api_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDNoCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDNoCheckReq) ProtoMessage() {}

func (x *IDNoCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDNoCheckReq.ProtoReflect.Descriptor instead.
func (*IDNoCheckReq) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *IDNoCheckReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IDNoCheckReq) GetIdno() string {
	if x != nil {
		return x.Idno
	}
	return ""
}

type IDNoCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDNoCheckResp) Reset() {
	*x = IDNoCheckResp{}
	mi := &file_api_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDNoCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDNoCheckResp) ProtoMessage() {}

func (x *IDNoCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDNoCheckResp.ProtoReflect.Descriptor instead.
func (*IDNoCheckResp) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *IDNoCheckResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IDNoCheckResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IDNoCheckResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetVerifyCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeReq) Reset() {
	*x = GetVerifyCodeReq{}
	mi := &file_api_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReq) ProtoMessage() {}

func (x *GetVerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReq.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *GetVerifyCodeReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

type GetVerifyCodeResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VerifyCode     string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	VerifyCodeTime int64                  `protobuf:"varint,4,opt,name=verify_code_time,json=verifyCodeTime,proto3" json:"verify_code_time,omitempty"`
	VerifyCodeLife int64                  `protobuf:"varint,5,opt,name=verify_code_life,json=verifyCodeLife,proto3" json:"verify_code_life,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVerifyCodeResp) Reset() {
	*x = GetVerifyCodeResp{}
	mi := &file_api_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeResp) ProtoMessage() {}

func (x *GetVerifyCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeResp.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeResp) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *GetVerifyCodeResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVerifyCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVerifyCodeResp) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *GetVerifyCodeResp) GetVerifyCodeTime() int64 {
	if x != nil {
		return x.VerifyCodeTime
	}
	return 0
}

func (x *GetVerifyCodeResp) GetVerifyCodeLife() int64 {
	if x != nil {
		return x.VerifyCodeLife
	}
	return 0
}

// 提交电话号码请求消息
type SubmitPhoneReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPhoneReq) Reset() {
	*x = SubmitPhoneReq{}
	mi := &file_api_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPhoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPhoneReq) ProtoMessage() {}

func (x *SubmitPhoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPhoneReq.ProtoReflect.Descriptor instead.
func (*SubmitPhoneReq) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitPhoneReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

type SubmitPhoneResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPhoneResp) Reset() {
	*x = SubmitPhoneResp{}
	mi := &file_api_driver_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPhoneResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPhoneResp) ProtoMessage() {}

func (x *SubmitPhoneResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPhoneResp.ProtoReflect.Descriptor instead.
func (*SubmitPhoneResp) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitPhoneResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SubmitPhoneResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubmitPhoneResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_driver_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{6}
}

func (x *LoginReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *LoginReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type LoginResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token          string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	TokenCreatedAt int64                  `protobuf:"varint,4,opt,name=token_created_at,json=tokenCreatedAt,proto3" json:"token_created_at,omitempty"`
	TokenLife      int32                  `protobuf:"varint,5,opt,name=token_life,json=tokenLife,proto3" json:"token_life,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_api_driver_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetTokenCreatedAt() int64 {
	if x != nil {
		return x.TokenCreatedAt
	}
	return 0
}

func (x *LoginResp) GetTokenLife() int32 {
	if x != nil {
		return x.TokenLife
	}
	return 0
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_api_driver_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{8}
}

type LogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_api_driver_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_driver_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_api_driver_driver_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LogoutResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_driver_driver_proto protoreflect.FileDescriptor

const file_api_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x17api/driver/driver.proto\x12\n" +
	"api.driver\x1a\x1cgoogle/api/annotations.proto\"6\n" +
	"\fIDNoCheckReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04idno\x18\x02 \x01(\tR\x04idno\"U\n" +
	"\rIDNoCheckResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"0\n" +
	"\x10GetVerifyCodeReq\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\"\xb6\x01\n" +
	"\x11GetVerifyCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\x12(\n" +
	"\x10verify_code_time\x18\x04 \x01(\x03R\x0everifyCodeTime\x12(\n" +
	"\x10verify_code_life\x18\x05 \x01(\x03R\x0everifyCodeLife\".\n" +
	"\x0eSubmitPhoneReq\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\"W\n" +
	"\x0fSubmitPhoneResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"I\n" +
	"\bLoginReq\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\x12\x1f\n" +
	"\vverify_code\x18\x02 \x01(\tR\n" +
	"verifyCode\"\x98\x01\n" +
	"\tLoginResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12(\n" +
	"\x10token_created_at\x18\x04 \x01(\x03R\x0etokenCreatedAt\x12\x1d\n" +
	"\n" +
	"token_life\x18\x05 \x01(\x05R\ttokenLife\"\v\n" +
	"\tLogoutReq\":\n" +
	"\n" +
	"LogoutResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xee\x03\n" +
	"\x06Driver\x12_\n" +
	"\tIDNoCheck\x12\x18.api.driver.IDNoCheckReq\x1a\x19.api.driver.IDNoCheckResp\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/driver/idno-check\x12y\n" +
	"\rGetVerifyCode\x12\x1c.api.driver.GetVerifyCodeReq\x1a\x1d.api.driver.GetVerifyCodeResp\"+\x82\xd3\xe4\x93\x02%\x12#/driver/get-verify-code/{telephone}\x12g\n" +
	"\vSubmitPhone\x12\x1a.api.driver.SubmitPhoneReq\x1a\x1b.api.driver.SubmitPhoneResp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/driver/submit-phone\x12N\n" +
	"\x05Login\x12\x14.api.driver.LoginReq\x1a\x15.api.driver.LoginResp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/driver/login\x12O\n" +
	"\x06Logout\x12\x15.api.driver.LogoutReq\x1a\x16.api.driver.LogoutResp\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/driver/logoutB\x1aZ\x18driver/api/driver;driverb\x06proto3"

var (
	file_api_driver_driver_proto_rawDescOnce sync.Once
	file_api_driver_driver_proto_rawDescData []byte
)

func file_api_driver_driver_proto_rawDescGZIP() []byte {
	file_api_driver_driver_proto_rawDescOnce.Do(func() {
		file_api_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_driver_driver_proto_rawDesc), len(file_api_driver_driver_proto_rawDesc)))
	})
	return file_api_driver_driver_proto_rawDescData
}

var file_api_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_driver_driver_proto_goTypes = []any{
	(*IDNoCheckReq)(nil),      // 0: api.driver.IDNoCheckReq
	(*IDNoCheckResp)(nil),     // 1: api.driver.IDNoCheckResp
	(*GetVerifyCodeReq)(nil),  // 2: api.driver.GetVerifyCodeReq
	(*GetVerifyCodeResp)(nil), // 3: api.driver.GetVerifyCodeResp
	(*SubmitPhoneReq)(nil),    // 4: api.driver.SubmitPhoneReq
	(*SubmitPhoneResp)(nil),   // 5: api.driver.SubmitPhoneResp
	(*LoginReq)(nil),          // 6: api.driver.LoginReq
	(*LoginResp)(nil),         // 7: api.driver.LoginResp
	(*LogoutReq)(nil),         // 8: api.driver.LogoutReq
	(*LogoutResp)(nil),        // 9: api.driver.LogoutResp
}
var file_api_driver_driver_proto_depIdxs = []int32{
	0, // 0: api.driver.Driver.IDNoCheck:input_type -> api.driver.IDNoCheckReq
	2, // 1: api.driver.Driver.GetVerifyCode:input_type -> api.driver.GetVerifyCodeReq
	4, // 2: api.driver.Driver.SubmitPhone:input_type -> api.driver.SubmitPhoneReq
	6, // 3: api.driver.Driver.Login:input_type -> api.driver.LoginReq
	8, // 4: api.driver.Driver.Logout:input_type -> api.driver.LogoutReq
	1, // 5: api.driver.Driver.IDNoCheck:output_type -> api.driver.IDNoCheckResp
	3, // 6: api.driver.Driver.GetVerifyCode:output_type -> api.driver.GetVerifyCodeResp
	5, // 7: api.driver.Driver.SubmitPhone:output_type -> api.driver.SubmitPhoneResp
	7, // 8: api.driver.Driver.Login:output_type -> api.driver.LoginResp
	9, // 9: api.driver.Driver.Logout:output_type -> api.driver.LogoutResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_driver_driver_proto_init() }
func file_api_driver_driver_proto_init() {
	if File_api_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_driver_driver_proto_rawDesc), len(file_api_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_driver_driver_proto_goTypes,
		DependencyIndexes: file_api_driver_driver_proto_depIdxs,
		MessageInfos:      file_api_driver_driver_proto_msgTypes,
	}.Build()
	File_api_driver_driver_proto = out.File
	file_api_driver_driver_proto_goTypes = nil
	file_api_driver_driver_proto_depIdxs = nil
}
